package com.dream11.populator.constant;

public class Constants {
  public static final String ASSIGNMENT_COUNTER_CACHE_NAME = "ASSIGNMENT_COUNTER_CACHE";
  public static final String REQUIRED_ASSIGNMENT_COUNTER_CACHE_NAME = "REQUIRED_ASSIGNMENT_COUNTER_CACHE";
  public static final String SUCCESS_MESSAGE_PROCESSOR_COUNTER_CACHE_NAME = "SUCCESS_MESSAGE_PROCESSOR_COUNTER_CACHE";
  public static final String FAILED_MESSAGE_PROCESSOR_COUNTER_CACHE_NAME = "FAILED_MESSAGE_PROCESSOR_COUNTER_CACHE_NAME";
}
