from enum import Enum


class ComputeState(Enum):
    CLUSTER_CREATION_REQUEST_RECEIVED = "CLUSTER_CREATION_REQUEST_RECEIVED"
    CLUSTER_CREATED = "CLUSTER_CREATED"
    CLUSTER_CREATION_FAILED = "CLUSTER_CREATION_FAILED"
    CLUSTER_DELETION_REQUEST_RECEIVED = "CLUSTER_DELETION_REQUEST_RECEIVED"
    CLUSTER_DELETED = "CLUSTER_DELETED"
    CLUSTER_DELETION_FAILED = "CLUSTER_DELETION_FAILED"
    CLUSTER_UPDATION_REQUEST_RECEIVED = "CLUSTER_UPDATION_REQUEST_RECEIVED"
    CLUSTER_UPDATED = "CLUSTER_UPDATED"
    CLUSTER_UPDATION_FAILED = "CLUSTER_UPDATION_FAILED"
    CLUSTER_START_REQUEST_RECEIVED = "CLUSTER_START_REQUEST_RECEIVED"
    CLUSTER_START_FAILED = "CLUSTER_START_FAILED"
    CLUSTER_STOP_REQUEST_RECEIVED = "CLUSTER_STOP_REQUEST_RECEIVED"
    CLUSTER_STOPPED = "CLUSTER_STOPPED"
    CLUSTER_STOP_FAILED = "CLUSTER_STOP_FAILED"
    CLUSTER_RESTART_REQUEST_RECEIVED = "CLUSTER_RESTART_REQUEST_RECEIVED"
    CLUSTER_RESTART_FAILED = "CLUSTER_RESTART_FAILED"
