#!/bin/sh
set -e

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║           Darwin Distribution - Initial Setup                   ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Check if yq is available
if ! command -v yq >/dev/null 2>&1; then
  echo "❌ yq is required but not installed."
  echo "   Please run setup.sh first to install dependencies, or install yq manually."
  exit 1
fi

# Check if services.yaml exists
YAML_FILE="services.yaml"
if [ ! -f "$YAML_FILE" ]; then
  echo "❌ services.yaml not found in current directory."
  exit 1
fi

# Create .setup directory if it doesn't exist
mkdir -p .setup

# Output file
OUTPUT_FILE=".setup/enabled-services.yaml"

# Parse command line arguments
ALL_YES=false
while [ $# -gt 0 ]; do
  case "$1" in
    --all)
      ALL_YES=true
      shift
      ;;
    *)
      echo "Unknown option: $1"
      echo "Usage: $0 [--all]"
      echo "  --all: Enable all services without prompts"
      exit 1
      ;;
  esac
done

# Check if config already exists
if [ -f "$OUTPUT_FILE" ]; then
  if [ "$ALL_YES" = "true" ]; then
    echo "⚠️  Configuration already exists. Overwriting (--all mode)..."
  else
    read -p "⚠️  Configuration already exists. Overwrite? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      echo "Keeping existing configuration."
      exit 0
    fi
  fi
fi

if [ "$ALL_YES" = "true" ]; then
  echo "Running in --all mode: Enabling all services without prompts."
else
  echo "This wizard will help you select which services to enable."
  echo "Answer y/n for each service."
fi
echo ""

# Initialize the output file
echo "# Darwin Distribution - Enabled Services Configuration" > "$OUTPUT_FILE"
echo "# Generated by init.sh on $(date)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# ============================================================================
# HELPER FUNCTION: Prompt with validation and 3 retries
# ============================================================================
# Usage: prompt_yn "prompt text" "default (y/n)"
# Sets global variable PROMPT_RESULT to "true" or "false"
PROMPT_RESULT=""

prompt_yn() {
  local prompt_text="$1"
  local default="$2"
  local retries=3
  local attempt=0
  
  while [ $attempt -lt $retries ]; do
    read -p "$prompt_text (y/n) " -n 1 -r
    echo
    
    # Handle empty response (use default)
    if [ -z "$REPLY" ]; then
      if [ "$default" = "y" ]; then
        PROMPT_RESULT="true"
      else
        PROMPT_RESULT="false"
      fi
      return 0
    fi
    
    # Handle valid y/n responses
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      PROMPT_RESULT="true"
      return 0
    elif [[ $REPLY =~ ^[Nn]$ ]]; then
      PROMPT_RESULT="false"
      return 0
    fi
    
    # Invalid input
    attempt=$((attempt + 1))
    remaining=$((retries - attempt))
    if [ $remaining -gt 0 ]; then
      echo "    ⚠️  Invalid input. Please enter 'y' or 'n'. ($remaining retries left)"
    fi
  done
  
  # After 3 retries, use default
  echo "    ⚠️  Using default: $default"
  if [ "$default" = "y" ]; then
    PROMPT_RESULT="true"
  else
    PROMPT_RESULT="false"
  fi
  return 0
}

# ============================================================================
# APPLICATIONS
# ============================================================================
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "                        APPLICATIONS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "applications:" >> "$OUTPUT_FILE"

COMPUTE_ENABLED=false
ML_SERVE_APP_ENABLED=false

app_count=$(yq eval '.applications | length' "$YAML_FILE")
i=0
while [ $i -lt $app_count ]; do
  app_name=$(yq eval ".applications[$i].application" "$YAML_FILE")
  default_enabled=$(yq eval ".applications[$i].enabled" "$YAML_FILE")
  
  # If --all flag is set, enable all applications
  if [ "$ALL_YES" = "true" ]; then
    enabled="true"
  else
    # Determine default for prompt
    if [ "$default_enabled" = "true" ]; then
      default="y"
    else
      default="n"
    fi
    
    # Prompt with validation
    prompt_yn "  Enable $app_name?" "$default"
    enabled="$PROMPT_RESULT"
  fi
  
  echo "  $app_name: $enabled" >> "$OUTPUT_FILE"
  
  # Track if darwin-compute is enabled for ray-images dependency
  if [ "$app_name" = "darwin-compute" ] && [ "$enabled" = "true" ]; then
    COMPUTE_ENABLED=true
  fi
  
  # Track if ml-serve-app is enabled for serve-images dependency
  if [ "$app_name" = "ml-serve-app" ] && [ "$enabled" = "true" ]; then
    ML_SERVE_APP_ENABLED=true
  fi
  
  i=$((i + 1))
done

echo "" >> "$OUTPUT_FILE"

# ============================================================================
# RAY IMAGES (auto-enabled if darwin-compute is enabled, no user prompt)
# ============================================================================
echo "ray-images:" >> "$OUTPUT_FILE"

# If --all flag is set, enable all ray images
if [ "$ALL_YES" = "true" ]; then
  COMPUTE_ENABLED=true
fi

ray_count=$(yq eval '.ray-images | length' "$YAML_FILE")
if [ "$ray_count" = "0" ] || [ "$ray_count" = "null" ]; then
  echo "  # No ray images defined" >> "$OUTPUT_FILE"
else
  i=0
  while [ $i -lt $ray_count ]; do
    image_name=$(yq eval ".ray-images[$i].image-name" "$YAML_FILE")
    
    if [ "$COMPUTE_ENABLED" = "true" ]; then
      enabled="true"
    else
      enabled="false"
    fi
    
    # Quote the image name since it contains colons
    echo "  \"$image_name\": $enabled" >> "$OUTPUT_FILE"
    
    i=$((i + 1))
  done
fi

echo "" >> "$OUTPUT_FILE"

# ============================================================================
# SERVE IMAGES (auto-enabled if ml-serve-app is enabled, no user prompt)
# ============================================================================
echo "serve-images:" >> "$OUTPUT_FILE"

# If --all flag is set, enable all serve images
if [ "$ALL_YES" = "true" ]; then
  ML_SERVE_APP_ENABLED=true
fi

serve_count=$(yq eval '.serve-images | length' "$YAML_FILE")
if [ "$serve_count" = "0" ] || [ "$serve_count" = "null" ]; then
  echo "  # No serve images defined" >> "$OUTPUT_FILE"
else
  i=0
  while [ $i -lt $serve_count ]; do
    image_name=$(yq eval ".serve-images[$i].image-name" "$YAML_FILE")
    
    if [ "$ML_SERVE_APP_ENABLED" = "true" ]; then
      enabled="true"
    else
      enabled="false"
    fi
    
    # Quote the image name since it contains colons
    echo "  \"$image_name\": $enabled" >> "$OUTPUT_FILE"
    
    i=$((i + 1))
  done
fi

echo "" >> "$OUTPUT_FILE"

# ============================================================================
# DATASTORES
# ============================================================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "                        DATASTORES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "datastores:" >> "$OUTPUT_FILE"

datastore_count=$(yq eval '.datastores | length' "$YAML_FILE")
if [ "$datastore_count" = "0" ] || [ "$datastore_count" = "null" ]; then
  echo "  # No datastores defined in services.yaml" >> "$OUTPUT_FILE"
  echo "⚠️  No datastores found in services.yaml"
else
  i=0
  while [ $i -lt $datastore_count ]; do
    ds_name=$(yq eval ".datastores[$i].name" "$YAML_FILE")
    default_enabled=$(yq eval ".datastores[$i].enabled" "$YAML_FILE")
    ds_image=$(yq eval ".datastores[$i].image" "$YAML_FILE")
    
    # If --all flag is set, enable all datastores
    if [ "$ALL_YES" = "true" ]; then
      enabled="true"
    else
      # Determine default for prompt
      if [ "$default_enabled" = "true" ]; then
        default="y"
      else
        default="n"
      fi
      
      # Prompt with validation
      prompt_yn "  Enable $ds_name ($ds_image)?" "$default"
      enabled="$PROMPT_RESULT"
    fi
    
    echo "  $ds_name: $enabled" >> "$OUTPUT_FILE"
    
    i=$((i + 1))
  done
fi

# ============================================================================
# CLI TOOLS
# ============================================================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "                        CLI TOOLS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "" >> "$OUTPUT_FILE"
echo "cli-tools:" >> "$OUTPUT_FILE"

HERMES_CLI_ENABLED=false

# If --all flag is set, enable hermes-cli
if [ "$ALL_YES" = "true" ]; then
  HERMES_CLI_ENABLED=true
else
  prompt_yn "  Enable hermes-cli (local installation)?" "n"
  if [ "$PROMPT_RESULT" = "true" ]; then
    HERMES_CLI_ENABLED=true
  fi
fi

echo "  hermes-cli: $HERMES_CLI_ENABLED" >> "$OUTPUT_FILE"

# ============================================================================
# SUMMARY
# ============================================================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "                        CONFIGURATION SAVED"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Configuration saved to: $OUTPUT_FILE"
echo ""
echo "Enabled services:"
echo ""

# Show enabled applications
echo "📦 Applications:"
yq eval '.applications | to_entries | .[] | select(.value == true) | "   ✓ " + .key' "$OUTPUT_FILE" 2>/dev/null || echo "   (none)"

# Show ray images only if compute is enabled
if [ "$COMPUTE_ENABLED" = "true" ]; then
  echo ""
  echo "🔷 Ray Images (auto-enabled with darwin-compute):"
  yq eval '.ray-images | to_entries | .[] | select(.value == true) | "   ✓ " + .key' "$OUTPUT_FILE" 2>/dev/null || echo "   (none)"
fi

# Show serve images only if ml-serve-app is enabled
if [ "$ML_SERVE_APP_ENABLED" = "true" ]; then
  echo ""
  echo "🚀 Serve Images (auto-enabled with ml-serve-app):"
  yq eval '.serve-images | to_entries | .[] | select(.value == true) | "   ✓ " + .key' "$OUTPUT_FILE" 2>/dev/null || echo "   (none)"
fi

echo ""
echo "🗄️  Datastores:"
yq eval '.datastores | to_entries | .[] | select(.value == true) | "   ✓ " + .key' "$OUTPUT_FILE" 2>/dev/null || echo "   (none)"

echo ""
echo "🛠️  CLI Tools:"
yq eval '.cli-tools | to_entries | .[] | select(.value == true) | "   ✓ " + .key' "$OUTPUT_FILE" 2>/dev/null || echo "   (none)"

echo ""
echo "Next steps:"
echo "  1. Run ./setup.sh to build images and set up the cluster"
echo "  2. Run ./start.sh to deploy the platform"
echo ""
