INSERT IGNORE INTO `cassandra_store_feature_group_metadata` (`name`, `version`, `feature_group_type`, `feature_group`,
                                                      `entity_name`, `state`, `owner`, `tags`, `description`,
                                                      `created_at`, `updated_at`)
VALUES ('test_feature_group_1', 'v1', 'ONLINE',
        '{\"features\": [{\"name\": \"col1\", \"tags\": [\"a\", \"b\"], \"type\": \"TEXT\", \"description\": \"something\"}, {\"name\": \"col2\", \"tags\": [\"a\", \"b\"], \"type\": \"ASCII\", \"description\": \"something\"}, {\"name\": \"col3\", \"tags\": [\"a\", \"b\"], \"type\": \"VARCHAR\", \"description\": \"something\"}, {\"name\": \"col4\", \"tags\": [\"a\", \"b\"], \"type\": \"BLOB\", \"description\": \"something\"}, {\"name\": \"col5\", \"tags\": [\"a\", \"b\"], \"type\": \"BOOLEAN\", \"description\": \"something\"}, {\"name\": \"col6\", \"tags\": [\"a\", \"b\"], \"type\": \"DECIMAL\", \"description\": \"something\"}, {\"name\": \"col7\", \"tags\": [\"a\", \"b\"], \"type\": \"DOUBLE\", \"description\": \"something\"}, {\"name\": \"col8\", \"tags\": [\"a\", \"b\"], \"type\": \"FLOAT\", \"description\": \"something\"}, {\"name\": \"col9\", \"tags\": [\"a\", \"b\"], \"type\": \"INT\", \"description\": \"something\"}, {\"name\": \"col10\", \"tags\": [\"a\", \"b\"], \"type\": \"BIGINT\", \"description\": \"something\"}, {\"name\": \"col11\", \"tags\": [\"a\", \"b\"], \"type\": \"TIMESTAMP\", \"description\": \"something\"}, {\"name\": \"col12\", \"tags\": [\"a\", \"b\"], \"type\": \"TIMEUUID\", \"description\": \"something\"}, {\"name\": \"col13\", \"tags\": [\"a\", \"b\"], \"type\": \"UUID\", \"description\": \"something\"}, {\"name\": \"col14\", \"tags\": [\"a\", \"b\"], \"type\": \"INET\", \"description\": \"something\"}, {\"name\": \"col15\", \"tags\": [\"a\", \"b\"], \"type\": \"VARINT\", \"description\": \"something\"}], \"entityName\": \"test_entity_1\", \"featureGroupName\": \"test_feature_group_1\", \"featureGroupType\": \"ONLINE\"}',
        'test_entity_1', 'LIVE', 'bot@dream11.com', '[\"t1\", \"t2\"]', 'some-description', '2024-02-20 08:57:08',
        '2024-02-20 08:57:08');

INSERT IGNORE INTO `cassandra_store_feature_group_metadata` (`name`, `version`, `feature_group_type`, `feature_group`,
                                                      `entity_name`, `state`, `owner`, `tags`, `description`,
                                                      `created_at`, `updated_at`)
VALUES ('test_feature_group_2', 'v1', 'ONLINE',
        '{\"features\": [{\"name\": \"col1\", \"tags\": [\"a\", \"b\"], \"type\": \"TEXT\", \"description\": \"something\"}, {\"name\": \"col2\", \"tags\": [\"a\", \"b\"], \"type\": \"ASCII\", \"description\": \"something\"}, {\"name\": \"col3\", \"tags\": [\"a\", \"b\"], \"type\": \"VARCHAR\", \"description\": \"something\"}, {\"name\": \"col4\", \"tags\": [\"a\", \"b\"], \"type\": \"BLOB\", \"description\": \"something\"}, {\"name\": \"col5\", \"tags\": [\"a\", \"b\"], \"type\": \"BOOLEAN\", \"description\": \"something\"}, {\"name\": \"col6\", \"tags\": [\"a\", \"b\"], \"type\": \"DECIMAL\", \"description\": \"something\"}, {\"name\": \"col7\", \"tags\": [\"a\", \"b\"], \"type\": \"DOUBLE\", \"description\": \"something\"}, {\"name\": \"col8\", \"tags\": [\"a\", \"b\"], \"type\": \"FLOAT\", \"description\": \"something\"}, {\"name\": \"col9\", \"tags\": [\"a\", \"b\"], \"type\": \"INT\", \"description\": \"something\"}, {\"name\": \"col10\", \"tags\": [\"a\", \"b\"], \"type\": \"BIGINT\", \"description\": \"something\"}, {\"name\": \"col11\", \"tags\": [\"a\", \"b\"], \"type\": \"TIMESTAMP\", \"description\": \"something\"}, {\"name\": \"col12\", \"tags\": [\"a\", \"b\"], \"type\": \"TIMEUUID\", \"description\": \"something\"}, {\"name\": \"col13\", \"tags\": [\"a\", \"b\"], \"type\": \"UUID\", \"description\": \"something\"}, {\"name\": \"col14\", \"tags\": [\"a\", \"b\"], \"type\": \"INET\", \"description\": \"something\"}, {\"name\": \"col15\", \"tags\": [\"a\", \"b\"], \"type\": \"VARINT\", \"description\": \"something\"}], \"entityName\": \"test_entity_1\", \"featureGroupName\": \"test_feature_group_2\", \"featureGroupType\": \"ONLINE\"}',
        'test_entity_1', 'LIVE', 'bot@dream11.com', '[\"t1\", \"t2\"]', 'some-description', '2024-02-20 08:57:08',
        '2024-02-20 08:57:08');

INSERT IGNORE INTO `cassandra_store_feature_group_metadata` (`name`, `version`, `feature_group_type`, `feature_group`,
                                                      `entity_name`, `state`, `owner`, `tags`, `description`,
                                                      `created_at`, `updated_at`)
VALUES ('test_feature_group_3', 'v1', 'ONLINE',
        '{\"features\": [{\"name\": \"col1\", \"tags\": [\"a\", \"b\"], \"type\": \"TEXT\", \"description\": \"something\"}, {\"name\": \"col2\", \"tags\": [\"a\", \"b\"], \"type\": \"ASCII\", \"description\": \"something\"}, {\"name\": \"col3\", \"tags\": [\"a\", \"b\"], \"type\": \"VARCHAR\", \"description\": \"something\"}, {\"name\": \"col4\", \"tags\": [\"a\", \"b\"], \"type\": \"BLOB\", \"description\": \"something\"}, {\"name\": \"col5\", \"tags\": [\"a\", \"b\"], \"type\": \"BOOLEAN\", \"description\": \"something\"}, {\"name\": \"col6\", \"tags\": [\"a\", \"b\"], \"type\": \"DECIMAL\", \"description\": \"something\"}, {\"name\": \"col7\", \"tags\": [\"a\", \"b\"], \"type\": \"DOUBLE\", \"description\": \"something\"}, {\"name\": \"col8\", \"tags\": [\"a\", \"b\"], \"type\": \"FLOAT\", \"description\": \"something\"}, {\"name\": \"col9\", \"tags\": [\"a\", \"b\"], \"type\": \"INT\", \"description\": \"something\"}, {\"name\": \"col10\", \"tags\": [\"a\", \"b\"], \"type\": \"BIGINT\", \"description\": \"something\"}, {\"name\": \"col11\", \"tags\": [\"a\", \"b\"], \"type\": \"TIMESTAMP\", \"description\": \"something\"}, {\"name\": \"col12\", \"tags\": [\"a\", \"b\"], \"type\": \"TIMEUUID\", \"description\": \"something\"}, {\"name\": \"col13\", \"tags\": [\"a\", \"b\"], \"type\": \"UUID\", \"description\": \"something\"}, {\"name\": \"col14\", \"tags\": [\"a\", \"b\"], \"type\": \"INET\", \"description\": \"something\"}, {\"name\": \"col15\", \"tags\": [\"a\", \"b\"], \"type\": \"VARINT\", \"description\": \"something\"}], \"entityName\": \"test_entity_2\", \"featureGroupName\": \"test_feature_group_3\", \"featureGroupType\": \"ONLINE\"}',
        'test_entity_2', 'LIVE', 'bot@dream11.com', '[\"t1\", \"t2\"]', 'some-description', '2024-02-20 08:57:08',
        '2024-02-20 08:57:08');



INSERT IGNORE INTO `cassandra_store_feature_group_metadata` (`name`, `version`, `feature_group_type`, `feature_group`,
                                                      `entity_name`, `state`, `owner`, `tags`, `description`,
                                                      `created_at`, `updated_at`)
VALUES ('test_feature_group_4', 'v1', 'ONLINE',
        '{\"features\": [{\"name\": \"col1\", \"tags\": [\"a\", \"b\"], \"type\": \"TEXT\", \"description\": \"something\"}, {\"name\": \"col2\", \"tags\": [\"a\", \"b\"], \"type\": \"ASCII\", \"description\": \"something\"}, {\"name\": \"col3\", \"tags\": [\"a\", \"b\"], \"type\": \"VARCHAR\", \"description\": \"something\"}, {\"name\": \"col4\", \"tags\": [\"a\", \"b\"], \"type\": \"BLOB\", \"description\": \"something\"}, {\"name\": \"col5\", \"tags\": [\"a\", \"b\"], \"type\": \"BOOLEAN\", \"description\": \"something\"}, {\"name\": \"col6\", \"tags\": [\"a\", \"b\"], \"type\": \"DECIMAL\", \"description\": \"something\"}, {\"name\": \"col7\", \"tags\": [\"a\", \"b\"], \"type\": \"DOUBLE\", \"description\": \"something\"}, {\"name\": \"col8\", \"tags\": [\"a\", \"b\"], \"type\": \"FLOAT\", \"description\": \"something\"}, {\"name\": \"col9\", \"tags\": [\"a\", \"b\"], \"type\": \"INT\", \"description\": \"something\"}, {\"name\": \"col10\", \"tags\": [\"a\", \"b\"], \"type\": \"BIGINT\", \"description\": \"something\"}, {\"name\": \"col11\", \"tags\": [\"a\", \"b\"], \"type\": \"TIMESTAMP\", \"description\": \"something\"}, {\"name\": \"col12\", \"tags\": [\"a\", \"b\"], \"type\": \"TIMEUUID\", \"description\": \"something\"}, {\"name\": \"col13\", \"tags\": [\"a\", \"b\"], \"type\": \"UUID\", \"description\": \"something\"}, {\"name\": \"col14\", \"tags\": [\"a\", \"b\"], \"type\": \"INET\", \"description\": \"something\"}, {\"name\": \"col15\", \"tags\": [\"a\", \"b\"], \"type\": \"VARINT\", \"description\": \"something\"}], \"entityName\": \"test_entity_2\", \"featureGroupName\": \"test_feature_group_4\", \"featureGroupType\": \"ONLINE\"}',
        'test_entity_2', 'LIVE', 'bot@dream11.com', '[\"t1\", \"t2\"]', 'some-description', '2024-02-20 08:57:08',
        '2024-02-20 08:57:08');

INSERT IGNORE INTO `cassandra_store_feature_group_metadata` (`name`, `version`, `feature_group_type`, `feature_group`,
                                                      `entity_name`, `state`, `owner`, `tags`, `description`,
                                                      `created_at`, `updated_at`)
VALUES ('test_feature_group_5', 'v1', 'ONLINE',
        '{\"features\": [{\"name\": \"col1\", \"tags\": [\"a\", \"b\"], \"type\": \"TEXT\", \"description\": \"something\"}, {\"name\": \"col2\", \"tags\": [\"a\", \"b\"], \"type\": \"ASCII\", \"description\": \"something\"}, {\"name\": \"col3\", \"tags\": [\"a\", \"b\"], \"type\": \"VARCHAR\", \"description\": \"something\"}, {\"name\": \"col4\", \"tags\": [\"a\", \"b\"], \"type\": \"BLOB\", \"description\": \"something\"}, {\"name\": \"col5\", \"tags\": [\"a\", \"b\"], \"type\": \"BOOLEAN\", \"description\": \"something\"}, {\"name\": \"col6\", \"tags\": [\"a\", \"b\"], \"type\": \"DECIMAL\", \"description\": \"something\"}, {\"name\": \"col7\", \"tags\": [\"a\", \"b\"], \"type\": \"DOUBLE\", \"description\": \"something\"}, {\"name\": \"col8\", \"tags\": [\"a\", \"b\"], \"type\": \"FLOAT\", \"description\": \"something\"}, {\"name\": \"col9\", \"tags\": [\"a\", \"b\"], \"type\": \"INT\", \"description\": \"something\"}, {\"name\": \"col10\", \"tags\": [\"a\", \"b\"], \"type\": \"BIGINT\", \"description\": \"something\"}, {\"name\": \"col11\", \"tags\": [\"a\", \"b\"], \"type\": \"TIMESTAMP\", \"description\": \"something\"}, {\"name\": \"col12\", \"tags\": [\"a\", \"b\"], \"type\": \"TIMEUUID\", \"description\": \"something\"}, {\"name\": \"col13\", \"tags\": [\"a\", \"b\"], \"type\": \"UUID\", \"description\": \"something\"}, {\"name\": \"col14\", \"tags\": [\"a\", \"b\"], \"type\": \"INET\", \"description\": \"something\"}, {\"name\": \"col15\", \"tags\": [\"a\", \"b\"], \"type\": \"VARINT\", \"description\": \"something\"}], \"entityName\": \"test_entity_3\", \"featureGroupName\": \"test_feature_group_5\", \"featureGroupType\": \"ONLINE\"}',
        'test_entity_3', 'LIVE', 'bot@dream11.com', '[\"t1\", \"t2\"]', 'some-description', '2024-02-20 08:57:08',
        '2024-02-20 08:57:08');



INSERT IGNORE INTO `cassandra_store_feature_group_metadata` (`name`, `version`, `feature_group_type`, `feature_group`,
                                                      `entity_name`, `state`, `owner`, `tags`, `description`,
                                                      `created_at`, `updated_at`)
VALUES ('test_feature_group_6', 'v1', 'ONLINE',
        '{\"features\": [{\"name\": \"col1\", \"tags\": [\"a\", \"b\"], \"type\": \"TEXT\", \"description\": \"something\"}, {\"name\": \"col2\", \"tags\": [\"a\", \"b\"], \"type\": \"ASCII\", \"description\": \"something\"}, {\"name\": \"col3\", \"tags\": [\"a\", \"b\"], \"type\": \"VARCHAR\", \"description\": \"something\"}, {\"name\": \"col4\", \"tags\": [\"a\", \"b\"], \"type\": \"BLOB\", \"description\": \"something\"}, {\"name\": \"col5\", \"tags\": [\"a\", \"b\"], \"type\": \"BOOLEAN\", \"description\": \"something\"}, {\"name\": \"col6\", \"tags\": [\"a\", \"b\"], \"type\": \"DECIMAL\", \"description\": \"something\"}, {\"name\": \"col7\", \"tags\": [\"a\", \"b\"], \"type\": \"DOUBLE\", \"description\": \"something\"}, {\"name\": \"col8\", \"tags\": [\"a\", \"b\"], \"type\": \"FLOAT\", \"description\": \"something\"}, {\"name\": \"col9\", \"tags\": [\"a\", \"b\"], \"type\": \"INT\", \"description\": \"something\"}, {\"name\": \"col10\", \"tags\": [\"a\", \"b\"], \"type\": \"BIGINT\", \"description\": \"something\"}, {\"name\": \"col11\", \"tags\": [\"a\", \"b\"], \"type\": \"TIMESTAMP\", \"description\": \"something\"}, {\"name\": \"col12\", \"tags\": [\"a\", \"b\"], \"type\": \"TIMEUUID\", \"description\": \"something\"}, {\"name\": \"col13\", \"tags\": [\"a\", \"b\"], \"type\": \"UUID\", \"description\": \"something\"}, {\"name\": \"col14\", \"tags\": [\"a\", \"b\"], \"type\": \"INET\", \"description\": \"something\"}, {\"name\": \"col15\", \"tags\": [\"a\", \"b\"], \"type\": \"VARINT\", \"description\": \"something\"}], \"entityName\": \"test_entity_3\", \"featureGroupName\": \"test_feature_group_6\", \"featureGroupType\": \"ONLINE\"}',
        'test_entity_3', 'LIVE', 'bot@dream11.com', '[\"t1\", \"t2\"]', 'some-description', '2024-02-20 08:57:08',
        '2024-02-20 08:57:08');


INSERT IGNORE INTO `cassandra_store_feature_group_metadata` (`name`, `version`, `feature_group_type`, `feature_group`,
                                                      `entity_name`, `state`, `owner`, `tags`, `description`,
                                                      `created_at`, `updated_at`)
VALUES ('test_feature_group_7', 'v1', 'ONLINE',
        '{\"features\": [{\"name\": \"col1\", \"tags\": [\"a\", \"b\"], \"type\": \"TEXT\", \"description\": \"something\"}, {\"name\": \"col2\", \"tags\": [\"a\", \"b\"], \"type\": \"ASCII\", \"description\": \"something\"}, {\"name\": \"col3\", \"tags\": [\"a\", \"b\"], \"type\": \"VARCHAR\", \"description\": \"something\"}, {\"name\": \"col4\", \"tags\": [\"a\", \"b\"], \"type\": \"BLOB\", \"description\": \"something\"}, {\"name\": \"col5\", \"tags\": [\"a\", \"b\"], \"type\": \"BOOLEAN\", \"description\": \"something\"}, {\"name\": \"col6\", \"tags\": [\"a\", \"b\"], \"type\": \"DECIMAL\", \"description\": \"something\"}, {\"name\": \"col7\", \"tags\": [\"a\", \"b\"], \"type\": \"DOUBLE\", \"description\": \"something\"}, {\"name\": \"col8\", \"tags\": [\"a\", \"b\"], \"type\": \"FLOAT\", \"description\": \"something\"}, {\"name\": \"col9\", \"tags\": [\"a\", \"b\"], \"type\": \"INT\", \"description\": \"something\"}, {\"name\": \"col10\", \"tags\": [\"a\", \"b\"], \"type\": \"BIGINT\", \"description\": \"something\"}, {\"name\": \"col11\", \"tags\": [\"a\", \"b\"], \"type\": \"TIMESTAMP\", \"description\": \"something\"}, {\"name\": \"col12\", \"tags\": [\"a\", \"b\"], \"type\": \"TIMEUUID\", \"description\": \"something\"}, {\"name\": \"col13\", \"tags\": [\"a\", \"b\"], \"type\": \"UUID\", \"description\": \"something\"}, {\"name\": \"col14\", \"tags\": [\"a\", \"b\"], \"type\": \"INET\", \"description\": \"something\"}, {\"name\": \"col15\", \"tags\": [\"a\", \"b\"], \"type\": \"VARINT\", \"description\": \"something\"}], \"entityName\": \"test_entity_4\", \"featureGroupName\": \"test_feature_group_7\", \"featureGroupType\": \"ONLINE\"}',
        'test_entity_4', 'LIVE', 'bot@dream11.com', '[\"t1\", \"t2\"]', 'some-description', '2024-02-20 08:57:08',
        '2024-02-20 08:57:08');



INSERT IGNORE INTO `cassandra_store_feature_group_metadata` (`name`, `version`, `feature_group_type`, `feature_group`,
                                                      `entity_name`, `state`, `owner`, `tags`, `description`,
                                                      `created_at`, `updated_at`)
VALUES ('test_feature_group_8', 'v1', 'ONLINE',
        '{\"features\": [{\"name\": \"col1\", \"tags\": [\"a\", \"b\"], \"type\": \"TEXT\", \"description\": \"something\"}, {\"name\": \"col2\", \"tags\": [\"a\", \"b\"], \"type\": \"ASCII\", \"description\": \"something\"}, {\"name\": \"col3\", \"tags\": [\"a\", \"b\"], \"type\": \"VARCHAR\", \"description\": \"something\"}, {\"name\": \"col4\", \"tags\": [\"a\", \"b\"], \"type\": \"BLOB\", \"description\": \"something\"}, {\"name\": \"col5\", \"tags\": [\"a\", \"b\"], \"type\": \"BOOLEAN\", \"description\": \"something\"}, {\"name\": \"col6\", \"tags\": [\"a\", \"b\"], \"type\": \"DECIMAL\", \"description\": \"something\"}, {\"name\": \"col7\", \"tags\": [\"a\", \"b\"], \"type\": \"DOUBLE\", \"description\": \"something\"}, {\"name\": \"col8\", \"tags\": [\"a\", \"b\"], \"type\": \"FLOAT\", \"description\": \"something\"}, {\"name\": \"col9\", \"tags\": [\"a\", \"b\"], \"type\": \"INT\", \"description\": \"something\"}, {\"name\": \"col10\", \"tags\": [\"a\", \"b\"], \"type\": \"BIGINT\", \"description\": \"something\"}, {\"name\": \"col11\", \"tags\": [\"a\", \"b\"], \"type\": \"TIMESTAMP\", \"description\": \"something\"}, {\"name\": \"col12\", \"tags\": [\"a\", \"b\"], \"type\": \"TIMEUUID\", \"description\": \"something\"}, {\"name\": \"col13\", \"tags\": [\"a\", \"b\"], \"type\": \"UUID\", \"description\": \"something\"}, {\"name\": \"col14\", \"tags\": [\"a\", \"b\"], \"type\": \"INET\", \"description\": \"something\"}, {\"name\": \"col15\", \"tags\": [\"a\", \"b\"], \"type\": \"VARINT\", \"description\": \"something\"}], \"entityName\": \"test_entity_4\", \"featureGroupName\": \"test_feature_group_8\", \"featureGroupType\": \"ONLINE\"}',
        'test_entity_4', 'LIVE', 'bot@dream11.com', '[\"t1\", \"t2\"]', 'some-description', '2024-02-20 08:57:08',
        '2024-02-20 08:57:08');


INSERT IGNORE INTO `cassandra_store_feature_group_metadata` (`name`, `version`, `feature_group_type`, `feature_group`,
                                                      `entity_name`, `state`, `owner`, `tags`, `description`,
                                                      `created_at`, `updated_at`)
VALUES ('test_feature_group_9', 'v1', 'ONLINE',
        '{\"features\": [{\"name\": \"col1\", \"tags\": [\"a\", \"b\"], \"type\": \"TEXT\", \"description\": \"something\"}, {\"name\": \"col2\", \"tags\": [\"a\", \"b\"], \"type\": \"ASCII\", \"description\": \"something\"}, {\"name\": \"col3\", \"tags\": [\"a\", \"b\"], \"type\": \"VARCHAR\", \"description\": \"something\"}, {\"name\": \"col4\", \"tags\": [\"a\", \"b\"], \"type\": \"BLOB\", \"description\": \"something\"}, {\"name\": \"col5\", \"tags\": [\"a\", \"b\"], \"type\": \"BOOLEAN\", \"description\": \"something\"}, {\"name\": \"col6\", \"tags\": [\"a\", \"b\"], \"type\": \"DECIMAL\", \"description\": \"something\"}, {\"name\": \"col7\", \"tags\": [\"a\", \"b\"], \"type\": \"DOUBLE\", \"description\": \"something\"}, {\"name\": \"col8\", \"tags\": [\"a\", \"b\"], \"type\": \"FLOAT\", \"description\": \"something\"}, {\"name\": \"col9\", \"tags\": [\"a\", \"b\"], \"type\": \"INT\", \"description\": \"something\"}, {\"name\": \"col10\", \"tags\": [\"a\", \"b\"], \"type\": \"BIGINT\", \"description\": \"something\"}, {\"name\": \"col11\", \"tags\": [\"a\", \"b\"], \"type\": \"TIMESTAMP\", \"description\": \"something\"}, {\"name\": \"col12\", \"tags\": [\"a\", \"b\"], \"type\": \"TIMEUUID\", \"description\": \"something\"}, {\"name\": \"col13\", \"tags\": [\"a\", \"b\"], \"type\": \"UUID\", \"description\": \"something\"}, {\"name\": \"col14\", \"tags\": [\"a\", \"b\"], \"type\": \"INET\", \"description\": \"something\"}, {\"name\": \"col15\", \"tags\": [\"a\", \"b\"], \"type\": \"VARINT\", \"description\": \"something\"}], \"entityName\": \"test_entity_5\", \"featureGroupName\": \"test_feature_group_9\", \"featureGroupType\": \"ONLINE\"}',
        'test_entity_5', 'LIVE', 'bot@dream11.com', '[\"t1\", \"t2\"]', 'some-description', '2024-02-20 08:57:08',
        '2024-02-20 08:57:08');



INSERT IGNORE INTO `cassandra_store_feature_group_metadata` (`name`, `version`, `feature_group_type`, `feature_group`,
                                                      `entity_name`, `state`, `owner`, `tags`, `description`,
                                                      `created_at`, `updated_at`)
VALUES ('test_feature_group_10', 'v1', 'ONLINE',
        '{\"features\": [{\"name\": \"col1\", \"tags\": [\"a\", \"b\"], \"type\": \"TEXT\", \"description\": \"something\"}, {\"name\": \"col2\", \"tags\": [\"a\", \"b\"], \"type\": \"ASCII\", \"description\": \"something\"}, {\"name\": \"col3\", \"tags\": [\"a\", \"b\"], \"type\": \"VARCHAR\", \"description\": \"something\"}, {\"name\": \"col4\", \"tags\": [\"a\", \"b\"], \"type\": \"BLOB\", \"description\": \"something\"}, {\"name\": \"col5\", \"tags\": [\"a\", \"b\"], \"type\": \"BOOLEAN\", \"description\": \"something\"}, {\"name\": \"col6\", \"tags\": [\"a\", \"b\"], \"type\": \"DECIMAL\", \"description\": \"something\"}, {\"name\": \"col7\", \"tags\": [\"a\", \"b\"], \"type\": \"DOUBLE\", \"description\": \"something\"}, {\"name\": \"col8\", \"tags\": [\"a\", \"b\"], \"type\": \"FLOAT\", \"description\": \"something\"}, {\"name\": \"col9\", \"tags\": [\"a\", \"b\"], \"type\": \"INT\", \"description\": \"something\"}, {\"name\": \"col10\", \"tags\": [\"a\", \"b\"], \"type\": \"BIGINT\", \"description\": \"something\"}, {\"name\": \"col11\", \"tags\": [\"a\", \"b\"], \"type\": \"TIMESTAMP\", \"description\": \"something\"}, {\"name\": \"col12\", \"tags\": [\"a\", \"b\"], \"type\": \"TIMEUUID\", \"description\": \"something\"}, {\"name\": \"col13\", \"tags\": [\"a\", \"b\"], \"type\": \"UUID\", \"description\": \"something\"}, {\"name\": \"col14\", \"tags\": [\"a\", \"b\"], \"type\": \"INET\", \"description\": \"something\"}, {\"name\": \"col15\", \"tags\": [\"a\", \"b\"], \"type\": \"VARINT\", \"description\": \"something\"}], \"entityName\": \"test_entity_5\", \"featureGroupName\": \"test_feature_group_10\", \"featureGroupType\": \"ONLINE\"}',
        'test_entity_5', 'LIVE', 'bot@dream11.com', '[\"t1\", \"t2\"]', 'some-description', '2024-02-20 08:57:08',
        '2024-02-20 08:57:08');
