{
 "title": "Ray",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  { "title": "Ray Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Instance Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ray_cluster_active_nodes", "legendFormat": "Active Nodes ({{node_type}})" },
    { "expr": "ray_cluster_failed_nodes", "legendFormat": "Failed Nodes {{node_type}}" },
    { "expr": "ray_cluster_pending_nodes", "legendFormat": "Pending Nodes ({{node_type}})" }
   ]
  },
  {
   "title": "Ray Node Resource Utilization (Percentage)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ray_node_cpu_utilization{instance=~\"$Instance\"} * ray_node_cpu_count{instance=~\"$Instance\"}) / sum(ray_node_cpu_count{instance=~\"$Instance\"})",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "sum(ray_node_mem_used{instance=~\"$Instance\"}) * 100 / sum(ray_node_mem_total{instance=~\"$Instance\"})",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "sum(ray_node_disk_usage{instance=~\"$Instance\"}) * 100 / sum(ray_node_disk_usage{instance=~\"$Instance\"} + ray_node_disk_free{instance=~\"$Instance\"})",
     "legendFormat": "Disk Utilization"
    },
    {
     "expr": "ray_node_gpus_utilization{instance=~\"$Instance\"} * 100 / ray_node_gpus_available{instance=~\"$Instance\"}",
     "legendFormat": "GPUs Utilization"
    }
   ]
  },
  {
   "title": "Node CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "ray_node_cpu_utilization{instance=~\"$Instance\"} * ray_node_cpu_count{instance=~\"$Instance\"} / 100",
     "legendFormat": "CPU Usage: {{instance}}"
    },
    {
     "expr": "ray_node_cpu_count{instance=~\"$Instance\"}",
     "legendFormat": "CPU Count: {{instance}}"
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ray_node_mem_used{instance=~\"$Instance\"}",
     "legendFormat": "Memory Used: {{instance}}"
    },
    {
     "expr": "ray_node_mem_available{instance=~\"$Instance\"}",
     "legendFormat": "Memory Available: {{instance}}"
    },
    {
     "expr": "ray_node_mem_total{instance=~\"$Instance\"}",
     "legendFormat": "Memory Total: {{instance}}"
    }
   ]
  },
  {
   "title": "Node Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ray_node_disk_usage{instance=~\"$Instance\"}",
     "legendFormat": "Disk Used: {{instance}}"
    },
    {
     "expr": "ray_node_disk_usage{instance=~\"$Instance\"} / (ray_node_disk_utilization_percentage{instance=~\"$Instance\"} / 100)",
     "legendFormat": "Disk Total: {{instance}}"
    }
   ]
  },
  {
   "title": "Network Speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "ray_node_network_receive_speed{instance=~\"$Instance\"}",
     "legendFormat": "Network Receive: {{instance}}"
    },
    {
     "expr": "ray_node_network_send_speed{instance=~\"$Instance\"}",
     "legendFormat": "Network Send: {{instance}}"
    }
   ]
  },
  {
   "title": "Node GPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ray_node_gpus_utilization{instance=~\"$Instance\"} OR vector(0)",
     "legendFormat": "GPU Usage: {{instance}}"
    },
    {
     "expr": "ray_node_gpus_available{instance=~\"$Instance\"} OR vector(0)",
     "legendFormat": "GPU Available: {{instance}}"
    }
   ]
  },
  {
   "title": "Node GPU Memory (GRAM)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ray_node_gram_used{instance=~\"$Instance\"} or vector(0)",
     "legendFormat": "Used GRAM: {{instance}}"
    },
    {
     "expr": "ray_node_gram_available{instance=~\"$Instance\"} or vector(0)",
     "legendFormat": "Available GRAM: {{instance}}"
    },
    {
     "expr": "ray_node_gram_used{instance=~\"$Instance\"} + on(NodeAddress) node_gram_available{instance=~\"$Instance\"} or vector(0)",
     "legendFormat": "Total GRAM: {{instance}}"
    }
   ]
  }
 ]
}
{
 "title": "Spark Metrics Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Block Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Max Off Heap Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "BlockManager_memory_maxOffHeapMem_MB_Value",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Manager Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "BlockManager_memory_maxMem_MB_Value",
     "legendFormat": "Block Manager Max Mem"
    }
   ]
  },
  {
   "title": "Disk Space (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "BlockManager_disk_diskSpaceUsed_MB_Value",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max On Heap Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "BlockManager_memory_maxOnHeapMem_MB_Value",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "BlockManager_memory_memUsed_MB_Number",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Off Heap Memory Used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "BlockManager_memory_offHeapMemUsed_MB_Number",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "On Heap Memory Used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "BlockManager_memory_onHeapMemUsed_MB_Value",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "BlockManager_memory_remainingMem_MB_Value",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining OnHeap Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "BlockManager_memory_remainingOnHeapMem_MB_Value",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining OffHeap Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "BlockManager_memory_remainingOffHeapMem_MB_Value",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hive External Catalog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Partitions Fetched Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "HiveExternalCatalog_partitionsFetched_Count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "File Cache Hits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "HiveExternalCatalog_fileCacheHits_Count",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Code Generator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Source Code Size Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "CodeGenerator_sourceCodeSize_Mean",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "DAG Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Waiting Stages Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "DAGScheduler_stage_waitingStages_Value",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Running Stages Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "DAGScheduler_stage_runningStages_Value",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Stages Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "DAGScheduler_stage_failedStages_Value",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Live Listener Bus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events Posted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "LiveListenerBus_numEventsPosted_Count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Dropped Events Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "LiveListenerBus_queue_shared_numDroppedEvents_Count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Event Log Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "LiveListenerBus_queue_eventLog_size_Value",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "App Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Completed Stages Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "appStatus_stages_completedStages_Count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Skipped Stages Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "appStatus_stages_skippedStages_Count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Stages Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "appStatus_stages_failedStages_Count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Completed Tasks Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "appStatus_tasks_completedTasks_Count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Tasks Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "appStatus_tasks_failedTasks_Count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Succeeded Jobs Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "appStatus_jobs_succeededJobs_Count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Killed Tasks Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "appStatus_tasks_killedTasks_Count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed Jobs Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "appStatus_jobs_failedJobs_Count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Job Duration (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      { "expr": "appStatus_jobDuration_Value", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Executor Allocation Number",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number Executors To Add",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "ExecutorAllocationManager_executors_numberExecutorsToAdd_Value",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Max Needed Executors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "ExecutorAllocationManager_executors_numberMaxNeededExecutors_Value",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Executors Failed to Remove",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "ExecutorAllocationManager_executors_numberExecutorsPendingToRemove_Value",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Decommissioning Executors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "ExecutorAllocationManager_executors_numberDecommissioningExecutors_Value",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of All Executors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "ExecutorAllocationManager_executors_numberAllExecutors_Value",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Target Executors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "ExecutorAllocationManager_executors_numberTargetExecutors_Value",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Default Dashboard",
 "tags": [ "rayVersion:2.3.0" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "SessionName", "query": { "query": "label_values(SessionName)" } },
   { "name": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "data_source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Scheduler Task State",
   "type": "graph",
   "description": "Current number of tasks in a particular state.\n\nState: the task state, as described by rpc::TaskState proto in common.proto. Task resubmissions due to failures or object reconstruction are shown with (retry) in the label.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Tasks by Name",
   "type": "graph",
   "description": "Current number of (live) tasks with a particular name. Task resubmissions due to failures or object reconstruction are shown with (retry) in the label.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "tasks" }
   ],
   "targets": [
    {
     "expr": "sum(ray_tasks{IsRetry=\"0\",State!~\"FINISHED|FAILED\",SessionName=\"$SessionName\"}) by (Name)",
     "legendFormat": "{{Name}}"
    },
    {
     "expr": "sum(ray_tasks{IsRetry!=\"0\",State!~\"FINISHED|FAILED\",SessionName=\"$SessionName\"}) by (Name)",
     "legendFormat": "{{Name}} (retry)"
    }
   ]
  },
  {
   "title": "Scheduler Actor State",
   "type": "graph",
   "description": "Current number of actors in a particular state.\n\nState: the actor state, as described by rpc::ActorTableData proto in gcs.proto.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "actors" }
   ],
   "targets": [
    {
     "expr": "sum(ray_actors{SessionName=\"$SessionName\"}) by (State)",
     "legendFormat": "{{State}}"
    }
   ]
  },
  {
   "title": "Active Actors by Name",
   "type": "graph",
   "description": "Current number of (live) actors with a particular name.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "actors" }
   ],
   "targets": [
    {
     "expr": "sum(ray_actors{State!=\"DEAD\",SessionName=\"$SessionName\"}) by (Name)",
     "legendFormat": "{{Name}}"
    }
   ]
  },
  {
   "title": "Scheduler CPUs (logical slots)",
   "type": "graph",
   "description": "Logical CPU usage of Ray. The dotted line indicates the total number of CPUs. The logical CPU is allocated by `num_cpus` arguments from tasks and actors. PENDING means the number of CPUs that will be available when new nodes are up after the autoscaler scales up.\n\nNOTE: Ray's logical CPU is different from physical CPU usage. Ray's logical CPU is allocated by `num_cpus` arguments.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(ray_resources{Name=\"CPU\",State=\"USED\",SessionName=\"$SessionName\"}) by (instance)",
     "legendFormat": "CPU Usage: {{instance}}"
    },
    {
     "expr": "sum(ray_resources{Name=\"CPU\",SessionName=\"$SessionName\"})",
     "legendFormat": "MAX"
    },
    {
     "expr": "((sum(autoscaler_cluster_resources{resource=\"CPU\",SessionName=\"$SessionName\"}) or vector(0)) + (sum(autoscaler_pending_resources{resource=\"CPU\",SessionName=\"$SessionName\"}) or vector(0)) and (sum(autoscaler_cluster_resources{resource=\"CPU\",SessionName=\"$SessionName\"}) or vector(0)) + (sum(autoscaler_pending_resources{resource=\"CPU\",SessionName=\"$SessionName\"}) or vector(0)) > (sum(autoscaler_cluster_resources{resource=\"CPU\",SessionName=\"$SessionName\"}) or vector(0)))",
     "legendFormat": "MAX + PENDING"
    }
   ]
  },
  {
   "title": "Object Store Memory",
   "type": "graph",
   "description": "Object store memory usage by location. The dotted line indicates the object store memory capacity.\n\nLocation: where the memory was allocated, which is MMAP_SHM or MMAP_DISK to indicate memory-mapped page, SPILLED to indicate spillage to disk, and WORKER_HEAP for objects small enough to be inlined in worker memory. Refer to metric_defs.cc for more information.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_object_store_memory{SessionName=\"$SessionName\"} / 1e9) by (Location)",
     "legendFormat": "{{Location}}"
    },
    {
     "expr": "sum(ray_resources{Name=\"object_store_memory\",SessionName=\"$SessionName\"} / 1e9)",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Scheduler GPUs (logical slots)",
   "type": "graph",
   "description": "Logical GPU usage of Ray. The dotted line indicates the total number of GPUs. The logical GPU is allocated by `num_gpus` arguments from tasks and actors. PENDING means the number of GPUs that will be available when new nodes are up after the autoscaler scales up.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "GPUs" }
   ],
   "targets": [
    {
     "expr": "ray_resources{Name=\"GPU\",State=\"USED\",SessionName=\"$SessionName\"}",
     "legendFormat": "GPU Usage: {{instance}}"
    },
    {
     "expr": "sum(ray_resources{Name=\"GPU\",SessionName=\"$SessionName\"})",
     "legendFormat": "MAX"
    },
    {
     "expr": "((sum(autoscaler_cluster_resources{resource=\"GPU\",SessionName=\"$SessionName\"}) or vector(0)) + (sum(autoscaler_pending_resources{resource=\"GPU\",SessionName=\"$SessionName\"}) or vector(0)) and (sum(autoscaler_cluster_resources{resource=\"GPU\",SessionName=\"$SessionName\"}) or vector(0)) + (sum(autoscaler_pending_resources{resource=\"GPU\",SessionName=\"$SessionName\"}) or vector(0)) > (sum(autoscaler_cluster_resources{resource=\"GPU\",SessionName=\"$SessionName\"}) or vector(0)))",
     "legendFormat": "MAX + PENDING"
    }
   ]
  },
  {
   "title": "Scheduler Placement Groups",
   "type": "graph",
   "description": "Current number of placement groups in a particular state.\n\nState: the placement group state, as described by the rpc::PlacementGroupTable proto in gcs.proto.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "placement groups" }
   ],
   "targets": [
    {
     "expr": "sum(ray_placement_groups{SessionName=\"$SessionName\"}) by (State)",
     "legendFormat": "{{State}}"
    }
   ]
  },
  {
   "title": "Node CPU (hardware utilization)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "ray_node_cpu_utilization{instance=~\"$Instance\",SessionName=\"$SessionName\"} * ray_node_cpu_count{instance=~\"$Instance\",SessionName=\"$SessionName\"} / 100",
     "legendFormat": "CPU Usage: {{instance}}"
    },
    {
     "expr": "sum(ray_node_cpu_count{SessionName=\"$SessionName\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node GPU (hardware utilization)",
   "type": "graph",
   "description": "Node's physical (hardware) GPU usage. The dotted line means the total number of hardware GPUs from the cluster. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "GPUs" }
   ],
   "targets": [
    {
     "expr": "ray_node_gpus_utilization{instance=~\"$Instance\",SessionName=\"$SessionName\"} / 100",
     "legendFormat": "GPU Usage: {{instance}}"
    },
    {
     "expr": "sum(ray_node_gpus_available{SessionName=\"$SessionName\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node Disk",
   "type": "graph",
   "description": "Node's physical (hardware) disk usage. The dotted line means the total amount of disk space from the cluster.\n\nNOTE: When Ray is deployed within a container, this shows the disk usage from the host machine. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ray_node_disk_usage{instance=~\"$Instance\",SessionName=\"$SessionName\"}",
     "legendFormat": "Disk Used: {{instance}}"
    },
    {
     "expr": "sum(ray_node_disk_free{SessionName=\"$SessionName\"}) + sum(ray_node_disk_usage{SessionName=\"$SessionName\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node Disk IO Speed",
   "type": "graph",
   "description": "Disk IO per node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ray_node_disk_io_write_speed{instance=~\"$Instance\",SessionName=\"$SessionName\"}",
     "legendFormat": "Write: {{instance}}"
    },
    {
     "expr": "ray_node_disk_io_read_speed{instance=~\"$Instance\",SessionName=\"$SessionName\"}",
     "legendFormat": "Read: {{instance}}"
    }
   ]
  },
  {
   "title": "Node Memory (heap + object store)",
   "type": "graph",
   "description": "The physical (hardware) memory usage for each node. The dotted line means the total amount of memory from the cluster. Node memory is a sum of object store memory (shared memory) and heap memory.\n\nNote: If Ray is deployed within a container, the total memory could be lower than the host machine because Ray may reserve some additional memory space outside the container.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ray_node_mem_used{instance=~\"$Instance\",SessionName=\"$SessionName\"}",
     "legendFormat": "Memory Used: {{instance}}"
    },
    {
     "expr": "sum(ray_node_mem_total{SessionName=\"$SessionName\"})",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node Memory by Component",
   "type": "graph",
   "description": "The physical (hardware) memory usage across the cluster, broken down by component. This reports the summed USS (unique set size) per Ray component. Ray components consist of system components (e.g., raylet, gcs, dashboard, or agent) and the method names of running tasks/actors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_component_uss_mb{SessionName=\"$SessionName\"} * 1e6) by (Component)",
     "legendFormat": "{{Component}}"
    }
   ]
  },
  {
   "title": "Node CPU by Component",
   "type": "graph",
   "description": "The physical (hardware) CPU usage across the cluster, broken down by component. This reports the summed CPU usage per Ray component. Ray components consist of system components (e.g., raylet, gcs, dashboard, or agent) and the method names of running tasks/actors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(ray_component_cpu_percentage{SessionName=\"$SessionName\"}) by (Component) / 100",
     "legendFormat": "{{Component}}"
    }
   ]
  },
  {
   "title": "Node GPU Memory (GRAM)",
   "type": "graph",
   "description": "The physical (hardware) GPU memory usage for each node. The dotted line means the total amount of GPU memory from the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ray_node_gram_used{instance=~\"$Instance\",SessionName=\"$SessionName\"} * 1024 * 1024",
     "legendFormat": "Used GRAM: {{instance}}"
    },
    {
     "expr": "(sum(ray_node_gram_available{SessionName=\"$SessionName\"}) + sum(ray_node_gram_used{SessionName=\"$SessionName\"})) * 1024 * 1024",
     "legendFormat": "MAX"
    }
   ]
  },
  {
   "title": "Node Network",
   "type": "graph",
   "description": "Network speed per node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ray_node_network_receive_speed{instance=~\"$Instance\",SessionName=\"$SessionName\"}",
     "legendFormat": "Recv: {{instance}}"
    },
    {
     "expr": "ray_node_network_send_speed{instance=~\"$Instance\",SessionName=\"$SessionName\"}",
     "legendFormat": "Send: {{instance}}"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "graph",
   "description": "A total number of active failed, and pending nodes from the cluster. \n\nACTIVE: A node is alive and available.\n\nFAILED: A node is dead and not available. The node is considered dead when the raylet process on the node is terminated. The node will get into the failed state if it cannot be provided (e.g., there's no available node from the cloud provider) or failed to setup (e.g., setup_commands have errors). \n\nPending: A node is being started by the Ray cluster launcher. The node is unavailable now because it is being provisioned and initialized.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "nodes" }
   ],
   "targets": [
    {
     "expr": "sum(ray_cluster_active_nodes{SessionName=\"$SessionName\"}) by (node_type)",
     "legendFormat": "Active Nodes: {{node_type}}"
    },
    {
     "expr": "sum(ray_cluster_failed_nodes{SessionName=\"$SessionName\"}) by (node_type)",
     "legendFormat": "Failed Nodes: {{node_type}}"
    },
    {
     "expr": "sum(ray_cluster_pending_nodes{SessionName=\"$SessionName\"}) by (node_type)",
     "legendFormat": "Pending Nodes: {{node_type}}"
    }
   ]
  },
  {
   "title": "Cluster Utilization",
   "type": "graph",
   "description": "Aggregated utilization of all physical resources (CPU, GPU, memory, disk, or etc.) across the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "avg(ray_node_cpu_utilization{SessionName=\"$SessionName\"})",
     "legendFormat": "CPU (physical)"
    },
    {
     "expr": "sum(ray_node_gpus_utilization{SessionName=\"$SessionName\"}) / on() (sum(autoscaler_cluster_resources{resource='GPU',SessionName=\"$SessionName\"}) or vector(0))",
     "legendFormat": "GPU (physical)"
    },
    {
     "expr": "sum(ray_node_mem_used{SessionName=\"$SessionName\"}) / on() (sum(ray_node_mem_total{SessionName=\"$SessionName\"})) * 100",
     "legendFormat": "Memory (RAM)"
    },
    {
     "expr": "sum(ray_node_gram_used{SessionName=\"$SessionName\"}) / on() (sum(ray_node_gram_available{SessionName=\"$SessionName\"}) + sum(ray_node_gram_used{SessionName=\"$SessionName\"})) * 100",
     "legendFormat": "GRAM"
    },
    {
     "expr": "sum(ray_object_store_memory{SessionName=\"$SessionName\"}) / on() sum(ray_resources{Name=\"object_store_memory\",SessionName=\"$SessionName\"}) * 100",
     "legendFormat": "Object Store Memory"
    },
    {
     "expr": "sum(ray_node_disk_usage{SessionName=\"$SessionName\"}) / on() (sum(ray_node_disk_free{SessionName=\"$SessionName\"}) + sum(ray_node_disk_usage{SessionName=\"$SessionName\"})) * 100",
     "legendFormat": "Disk"
    }
   ]
  }
 ]
}
{
 "title": "Ray - Updated",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Ray Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instance Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "ray_cluster_active_nodes", "legendFormat": "Active Nodes ({{node_type}})" },
    { "expr": "ray_cluster_failed_nodes", "legendFormat": "Failed Nodes {{node_type}}" },
    { "expr": "ray_cluster_pending_nodes", "legendFormat": "Pending Nodes ({{node_type}})" }
   ]
  },
  {
   "title": "Ray Node Resource Utilization (Percentage)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ray_node_cpu_utilization{instance=~\"$Instance\"} * ray_node_cpu_count{instance=~\"$Instance\"}) / sum(ray_node_cpu_count{instance=~\"$Instance\"})",
     "legendFormat": "CPU Utilization"
    },
    {
     "expr": "sum(ray_node_mem_used{instance=~\"$Instance\"}) * 100 / sum(ray_node_mem_total{instance=~\"$Instance\"})",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "sum(ray_node_disk_usage{instance=~\"$Instance\"}) * 100 / sum(ray_node_disk_usage{instance=~\"$Instance\"} + ray_node_disk_free{instance=~\"$Instance\"})",
     "legendFormat": "Disk Utilization"
    },
    {
     "expr": "ray_node_gpus_utilization{instance=~\"$Instance\"} * 100 / ray_node_gpus_available{instance=~\"$Instance\"}",
     "legendFormat": "GPUs Utilization"
    }
   ]
  },
  {
   "title": "Node CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sum(ray_node_cpu_utilization)", "legendFormat": "CPU Usage: {{instance}}" },
    { "expr": "sum(ray_node_cpu_count)", "legendFormat": "CPU Count: {{instance}}" }
   ]
  },
  {
   "title": "Node Disk",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "ray_node_disk_usage{instance=~\"$Instance\"}",
     "legendFormat": "Disk Used: {{instance}}"
    },
    {
     "expr": "ray_node_disk_usage{instance=~\"$Instance\"} / (ray_node_disk_utilization_percentage{instance=~\"$Instance\"} / 100)",
     "legendFormat": "Disk Total: {{instance}}"
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "sum(ray_node_mem_used)", "legendFormat": "Memory Used: {{instance}}" },
    { "expr": "sum(ray_node_mem_available)", "legendFormat": "Memory Available: {{instance}}" },
    { "expr": "sum(ray_node_mem_total)", "legendFormat": "Memory Total: {{instance}}" }
   ]
  },
  {
   "title": "Network Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(ray_node_network_receive_speed)",
     "legendFormat": "Network Receive: {{instance}}"
    },
    {
     "expr": "sum(ray_node_network_send_speed)",
     "legendFormat": "Network Send: {{instance}}"
    }
   ]
  },
  {
   "title": "Node GPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ray_node_gpus_utilization{instance=~\"$Instance\"} OR vector(0)",
     "legendFormat": "GPU Usage: {{instance}}"
    },
    {
     "expr": "ray_node_gpus_available{instance=~\"$Instance\"} OR vector(0)",
     "legendFormat": "GPU Available: {{instance}}"
    }
   ]
  },
  {
   "title": "Node GPU Memory (GRAM)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ray_node_gram_used{instance=~\"$Instance\"} or vector(0)",
     "legendFormat": "Used GRAM: {{instance}}"
    },
    {
     "expr": "ray_node_gram_available{instance=~\"$Instance\"} or vector(0)",
     "legendFormat": "Available GRAM: {{instance}}"
    },
    {
     "expr": "ray_node_gram_used{instance=~\"$Instance\"} + on(NodeAddress) node_gram_available{instance=~\"$Instance\"} or vector(0)",
     "legendFormat": "Total GRAM: {{instance}}"
    }
   ]
  }
 ]
}
{
 "title": "Serve Deployment Dashboard",
 "tags": [ "rayVersion:2.4.0" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Deployment",
    "query": {
     "query": "label_values(ray_serve_deployment_request_counter{}, deployment)"
    }
   },
   {
    "name": "Replica",
    "query": {
     "query": "label_values(ray_serve_deployment_request_counter{deployment=~\"$Deployment\",}, replica)"
    }
   },
   {
    "name": "Route",
    "query": {
     "query": "label_values(ray_serve_deployment_request_counter{deployment=~\"$Deployment\",}, route)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Deployments",
   "type": "timeseries",
   "description": "Number of replicas per deployment. Ignores \"Route\" variable.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(ray_serve_deployment_replica_healthy{deployment=~\"$Deployment\",replica=~\"$Replica\",}) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "QPS per replica",
   "type": "timeseries",
   "description": "QPS for each replica.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(ray_serve_deployment_request_counter{route=~\"$Route\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (deployment, replica)",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "P50 latency per replica",
   "type": "timeseries",
   "description": "P50 latency per replica.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (deployment, replica, le))",
     "legendFormat": "{{replica}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "P90 latency per replica",
   "type": "timeseries",
   "description": "P90 latency per replica.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (deployment, replica, le))",
     "legendFormat": "{{replica}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "P99 latency per replica",
   "type": "timeseries",
   "description": "P99 latency per replica.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (deployment, replica, le))",
     "legendFormat": "{{replica}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(ray_serve_deployment_processing_latency_ms_bucket{route=~\"$Route\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (le))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Queue size per deployment",
   "type": "timeseries",
   "description": "Number of requests queued per deployment. Ignores \"Replica\" and \"Route\" variable.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "sum(ray_serve_deployment_queued_queries{deployment=~\"$Deployment\",replica=~\"$Replica\",}) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Error QPS per replica",
   "type": "timeseries",
   "description": "Error QPS for each replica.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "sum(rate(ray_serve_deployment_error_counter{route=~\"$Route\",deployment=~\"$Deployment\",replica=~\"$Replica\",}[5m])) by (deployment, replica)",
     "legendFormat": "{{replica}}"
    }
   ]
  }
 ]
}