package com.dream11.app.constant;

public class Constants {
  public static final String SUCCESS_READ_COUNTERS_CACHE_NAME = "SUCCESS_READ_COUNTERS_CACHE";
  public static final String FAILED_READ_COUNTERS_CACHE_NAME = "FAILED_READ_COUNTERS_CACHE";

  public static final String SUCCESS_PARTITION_READ_COUNTERS_CACHE_NAME = "SUCCESS_PARTITION_READ_COUNTERS_CACHE";
  public static final String FAILED_PARTITION_READ_COUNTERS_CACHE_NAME = "FAILED_PARTITION_READ_COUNTERS_CACHE";
  public static final String SUCCESS_WRITE_COUNTERS_CACHE_NAME = "SUCCESS_WRITE_COUNTERS_CACHE";
  public static final String FAILED_WRITE_COUNTERS_CACHE_NAME = "FAILED_WRITE_COUNTERS_CACHE";
  public static final String SUCCESS_WRITE_COUNTERS_WITH_RUN_ID_CACHE_NAME =
      "SUCCESS_WRITE_COUNTERS_WITH_RUN_ID_CACHE";
  public static final String FAILED_WRITE_COUNTERS_WITH_RUN_ID_CACHE_NAME =
      "FAILED_WRITE_COUNTERS_WITH_RUN_ID_CACHE";
  public static final String WRITE_ROW_SIZE_DISTRIBUTION_SUMMARY_WITH_RUN_ID_CACHE_NAME =
      "WRITE_ROW_SIZE_DISTRIBUTION_SUMMARY_WITH_RUN_ID_CACHE";
  public static final String READ_ROW_SIZE_DISTRIBUTION_SUMMARY_CACHE_NAME = "READ_ROW_SIZE_DISTRIBUTION_SUMMARY_CACHE";
  public static final String PARTITION_READ_ROW_SIZE_DISTRIBUTION_SUMMARY_CACHE_NAME = "PARTITION_READ_ROW_SIZE_DISTRIBUTION_SUMMARY_CACHE";
  public static final String WRITE_ROW_SIZE_DISTRIBUTION_SUMMARY_CACHE_NAME = "WRITE_ROW_SIZE_DISTRIBUTION_SUMMARY_CACHE";
  public static final String READ_LATENCY_DISTRIBUTION_SUMMARY =
      "READ_LATENCY_DISTRIBUTION_SUMMARY";
}
