package darwincatalog.repository;

public class Queries {

  private Queries() {}

  public static final String ASSET_LINEAGE_RECURSIVE_CTE =
      "with RECURSIVE\n"
          + "    right_recursive_asset_lineage as (\n"
          + "        select\n"
          + "            id,\n"
          + "            from_asset_id,\n"
          + "            to_asset_id,\n"
          + "            created_at,\n"
          + "            updated_at,\n"
          + "            1 as level\n"
          + "        from\n"
          + "            asset_lineage\n"
          + "        where\n"
          + "            from_asset_id = :asset_id\n"
          + "        union all\n"
          + "        select\n"
          + "            al.id,\n"
          + "            al.from_asset_id,\n"
          + "            al.to_asset_id,\n"
          + "            al.created_at,\n"
          + "            al.updated_at,\n"
          + "            ral.level + 1\n"
          + "        from\n"
          + "            asset_lineage al\n"
          + "            join right_recursive_asset_lineage ral on al.from_asset_id = ral.to_asset_id\n"
          + "    ),\n"
          + "    left_recursive_asset_lineage as (\n"
          + "        select\n"
          + "            id,\n"
          + "            from_asset_id,\n"
          + "            to_asset_id,\n"
          + "            created_at,\n"
          + "            updated_at,\n"
          + "            1 as level\n"
          + "        from\n"
          + "            asset_lineage\n"
          + "        where\n"
          + "            to_asset_id = :asset_id\n"
          + "        union all\n"
          + "        select\n"
          + "            al.id,\n"
          + "            al.from_asset_id,\n"
          + "            al.to_asset_id,\n"
          + "            al.created_at,\n"
          + "            al.updated_at,\n"
          + "            lal.level + 1\n"
          + "        from\n"
          + "            asset_lineage al\n"
          + "            join left_recursive_asset_lineage lal on al.to_asset_id = lal.from_asset_id\n"
          + "    )\n"
          + "select\n"
          + "    id,\n"
          + "    from_asset_id,\n"
          + "    to_asset_id,\n"
          + "    created_at,\n"
          + "    updated_at\n"
          + "from\n"
          + "    right_recursive_asset_lineage\n"
          + "union all\n"
          + "select\n"
          + "    id,\n"
          + "    from_asset_id,\n"
          + "    to_asset_id,\n"
          + "    created_at,\n"
          + "    updated_at\n"
          + "from\n"
          + "    left_recursive_asset_lineage;";

  public static final String DOWNSTREAM_ASSET_ID_RECURSIVE_CTE =
      "WITH RECURSIVE\n"
          + "    downstream (asset_id) AS (\n"
          + "        SELECT\n"
          + "            to_asset_id\n"
          + "        FROM\n"
          + "            asset_lineage\n"
          + "        WHERE\n"
          + "            from_asset_id = :asset_id\n"
          + "        UNION\n"
          + "        SELECT\n"
          + "            al.to_asset_id\n"
          + "        FROM\n"
          + "            asset_lineage al\n"
          + "            JOIN downstream d ON al.from_asset_id = d.asset_id\n"
          + "    )\n"
          + "SELECT\n"
          + "    asset_id\n"
          + "FROM\n"
          + "    downstream;";
}
