from enum import Enum


class WorkspaceState(Enum):
    # events with values( event_name, severity )
    LAUNCH_CODESPACE_REQUESTED = ("LAUNCH_CODESPACE_REQUESTED", "INFO")
    LAUNCH_JOB_SUBMITTED = ("LAUNCH_JOB_SUBMITTED", "INFO")
    LAUNCH_JOB_SUCCESSFUL = ("LAUNCH_JOB_SUCCESSFUL", "INFO")
    LAUNCH_CODESPACE_FAILED = ("LAUNCH_CODESPACE_FAILED", "ERROR")
    SYNC_JOB_SUBMITTED = ("SYNC_JOB_SUBMITTED", "INFO")
    SYNC_JOB_RUNNING = ("SYNC_JOB_RUNNING", "INFO")
    LAUNCH_CODESPACE_SUCCESSFUL = ("LAUNCH_CODESPACE_SUCCESSFUL", "INFO")
    CREATE_PROJECT_REQUESTED = ("CREATE_PROJECT_REQUESTED", "INFO")
    CREATE_PROJECT_SUCCESSFUL = ("CREATE_PROJECT_SUCCESSFUL", "INFO")
    CREATE_CODESPACE_REQUESTED = ("CREATE_CODESPACE_REQUESTED", "INFO")
    CREATE_CODESPACE_SUCCESSFUL = ("CREATE_CODESPACE_SUCCESSFUL", "INFO")
    ATTACHED_CLUSTER = ("ATTACHED_CLUSTER", "INFO")
    DETACHED_CLUSTER = ("DETACHED_CLUSTER", "INFO")
    IMPORT_PROJECT_REQUESTED = ("IMPORT_PROJECT_REQUESTED", "INFO")
    IMPORT_JOB_SUBMITTED = ("IMPORT_JOB_SUBMITTED", "INFO")
    IMPORT_JOB_SUCCESSFUL = ("IMPORT_JOB_SUCCESSFUL", "INFO")
    IMPORT_PROJECT_SUCCESSFUL = ("IMPORT_PROJECT_SUCCESSFUL", "INFO")
    DELETE_CODESPACE_REQUESTED = ("DELETE_CODESPACE_REQUESTED", "INFO")
    DELETE_CODESPACE_SUCCESSFUL = ("DELETE_CODESPACE_SUCCESSFUL", "INFO")

    @property
    def event_name(self):
        return self.value[0]

    @property
    def severity(self):
        return self.value[1]
